### PR TITLE
Improve performance of Reader.php

### PR DESCRIPTION
**Pull request by FrancoisChaumont**
Buffering the database file in memory significantly improves the reader performance. 
Specially noticeable with very large amount of IP to search location for.

### CODE REVIEW

**Comment by FrancoisChaumont** [comment]
Not sure what went wrong with build job 426.6 (PHP: 7.2). 
I tested the changes on PHP 7.2.15 and it works great for me

**Comment by oschwald** [comment]
Some databases are hundreds of megabytes. We do not want to load the database into memory by default. This will also be much slower in situations where you are opening the database and only reading a single IP address. For this PR to be consider, the behavior would have to be optional and disabled by default.

**Comment by FrancoisChaumont** [comment]
Good point @oschwald. I will make changes accordingly. Thanks for the feedback

**Comment by FrancoisChaumont** [comment]
Not sure what is wrong with [build #432](https://travis-ci.org/maxmind/MaxMind-DB-Reader-php/builds/500541510). I was able to run the tests locally with no errors tho...

**Comment by oschwald** [comment]
The test is failing because the extension wasn't updated to handle the second argument. At the very least it should accept but ignore it. We would want to document that the argument has no effect when using the extension.

Is there a reason why you aren't using the extension to improve performance? You will see much more significant gains with that.

**Comment by oschwald** [comment]
Closing as this seems to have gone stale.

**Pull request closed without merging**
